server:
  port: 8081

spring:
  application:
    name: fraud-service
  datasource:
    username: 'root'
    password:
    url: jdbc:mysql://localhost:3306/cigma_spring_cloud_CUSTOMER?serverTimezone=UTC
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
        format_sql: true
    hibernate:
      ddl-auto: create-drop
      show-sql: true
